### ISSUE TITLE
Dyed item names using quark don't display w/ 'Show Modded Tooltips' enabled

### ISSUE THREAD

**Issue by build2stone** [Fuzss/consolehud#12]
With it disabled, the itemname is displayed in white (this is vanilla behaviour), with it enabled it is not displayed at all.

Suggestion: Support displaying dyed item names generally (Items with dyed names have an NBT-tag with the relevant info)

**Comment by Fuzss** [comment]
Quark is changing the text colour in a really weird way. This requires a Quark specific workaround. 

I'll look into it when I find the time to.

**Comment by Fuzss** [comment]
Feature is no longer present in current versions.
