### ISSUE TITLE
[1.12.2] Conflict with "Advent of Ascension". Game Crash when viewing some of AoA's Tooltips when held.

### ISSUE THREAD

**Issue by SonicX8000** [Fuzss/consolehud#13]
Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 3
AoA3-3.1.2.b
ConsoleHUD-v1.4.1-1.12.2
jei_1.12.2-4.15.0.279

Crash Reports:
https://pastebin.com/z8NUJdyJ

-----

First encountered with AoA's Hot Shot Gun where if you wield the item the game will crash the moment the tooltip appears.

AoA has quite a number of Weapons & Items so it's going to be tough to mark down whichever items that causes a crash. So far... it's the Hot Shot, Proton, Water-Balloon Bomber, Skeletal Bow, perhaps more as I go through the items.

I can get around this if I disable the "Held Items Tooltip" in Console HUD's config where the game won't crash.

The Console HUD config is at it's default setting while testing.

*EDIT*
There's another way to get around the crash it seems by setting the Rows to 1 which should only show the item name when held. Before it was set to 4.

**Comment by Fuzss** [comment]
Fixed in 1f44b26 for 1.14, will be ported to 1.12 at some point
