### ISSUE TITLE
More PaperDoll Options

### ISSUE THREAD

**Issue by sepsol** [Fuzss/consolehud#14]
a) an option to show paperdoll when attacking
b) an option to show paperdoll when walking
c) an option to show paperdoll when jumping
d) an option to show paperdoll when going prone (with [GoProne](https://www.curseforge.com/minecraft/mc-mods/goprone) mod)
e) an option to show paperdoll when carrying an item (with [Carry On](https://www.curseforge.com/minecraft/mc-mods/carry-on) mod)
f) an option to show paperdoll for anything you do but in first person
g) an option to show paperdoll always no matter 

also it would be great if paperdoll could show the entity that the player is riding in itself. like horses, pigs, boats, and even slabs and stairs they're sitting on (with [Sit](https://www.curseforge.com/minecraft/mc-mods/sit) mod)

**Comment by Fuzss** [comment]
Most of those suggestions are easy to implement, so I'll do that at some point. G is already an option, just set the display time to 0. I don't see how f is any different from g, could you be a bit more precise?
For the entity being ridden I'll have to play around with that a little, no promises though.

**Comment by sepsol** [comment]
Thanks for the answers and mentioning that time=0 thing, With (f) I meant that basically the paperdoll would be visible for only when you're in 3rd person. I can almost now distribute this to my friends! I just need #15 and #17 to be fixed and then I'll ditch Advanced Skin Customization xD

**Comment by Fuzss** [comment]
More display options were added in 1f44b26
