### ISSUE TITLE
Increase the framerate of PaperDoll

### ISSUE THREAD

**Issue by sepsol** [Fuzss/consolehud#15]
I tried [Advanced Skin Customization](https://www.curseforge.com/minecraft/mc-mods/advanced-skin-customization) before, yours have more options but is fairly more laggy compared to ASC. Please fix this.

**Comment by Fuzss** [comment]
As I've mentioned before I've already been able to fix the frame rate issue in e5ef872. I've now published a beta on Curse including this fix as it will probably take some time before the next major update is complete.

**Comment by sepsol** [comment]
Thank you so much! I'm gonna upload a side-by-side comparison with Advanced Skin Customization just for the record. The left one is Console HUD and the right one is ASC:

![Base Profile 2019 10 26 - 01 34 23 02_3](https://user-images.githubusercontent.com/47871887/67609533-289e5480-f79a-11e9-982f-bb162f04787e.gif)

**Comment by Fuzss** [comment]
Thanks for your effort. This was definitely fixed in e5ef872.

**Comment by sepsol** [comment]
Great! when will this update be released?

**Comment by Fuzss** [comment]
No idea like I’ve mentioned above. Please use the Preview version above including this fix.

**Comment by sepsol** [comment]
Thank you soooo much!

**Comment by sepsol** [comment]
I am testing the Preview version, I know it's preview and bugs are to be expected. I just want to report what I see:
- The FPS is MUCH better, actually it's fine.
- The right/left head swing is good, although I feel like the head moves too fast on the paperdoll.
- In my version the head doesn't seem to be moving up/down anymore 🤔 

**ConsoleHUD-v1.5-pre-1.14.4**

**Comment by sepsol** [comment]
Flying with Elytra looks much better on paperdoll as well.

**Comment by Fuzss** [comment]
The head is locked horizontally now as this is also the case in Console Edition.

**Comment by sepsol** [comment]
Can there be an option in the config file so that we can change this. We use our heads to signal yes/no to each other on our server and it is always nice to see how you're character's head really looks like from the outside in the paperdoll.

**Comment by Fuzss** [comment]
Will be added in beta 2. For the frame rate, that's been fixed in beta 1 on Curse now.

**Comment by sepsol** [comment]
Thanks
