### ISSUE TITLE
Head doesn't swing horizentally

### ISSUE THREAD

**Issue by sepsol** [Fuzss/consolehud#17]
The left one is Console HUD and the right one is Advanced Skin Customization mod (1.14.4-Forge): [GIF](https://www.dropbox.com/s/0na7hiwii6yhtbh/Base%20Profile%202019.10.26%20-%2001.34.23.02.gif?dl=1)

**Comment by Fuzss** [comment]
Has been completely overhauled in e5ef872 to mimic Console Edition more precisely.
