### ISSUE TITLE
When inventory is opened, the hotbar slot and chat is invisible

### ISSUE THREAD

**Issue by jho5245** [Fuzss/consolehud#21]
i think there may need to be toggle options to hide each gui (player doll, inventory, coord, etc) when inventory is opened.

**Comment by Fuzss** [comment]
The hud being hidden while any inventory is open is an intended feature as it's the same in Console Edition. If you don't want this to happen there is a config option called "Hide Hud In Container".

Gui enhancements offered by this mod like the paper doll and coordinate display are also hidden with said option enabled.
