### ISSUE TITLE
Compatibility with the Controllable mod

### ISSUE THREAD

**Issue by TheDirectorX** [Fuzss/consolehud#23]
### https://github.com/MrCrayfish/Controllable
**Controllable** is under development, so there are some problems when using both mods.
E.g., an interface shift:
![2020-03-11_01 44 50](https://user-images.githubusercontent.com/43481085/76357594-d2d9db80-6339-11ea-819d-e11e68217a65.png)

**Comment by Fuzss** [comment]
You can simple disable the floating hotbar feature in either one of both mods.
