### ISSUE TITLE
Quick save Icon Offset

### ISSUE THREAD

**Issue by Real2009XboxLiveKid** [Fuzss/consolehud#26]
it seems as though something has offset the entire options screen, aswell as the inventory screen, it its none of my other mods, because I've played with them all before adding this to the list. (Note: theres only 2 mods, and they're client side)
[Proof of bug.zip](https://github.com/Fuzss/consoleexperience/files/5154293/Proof.of.bug.zip)

**Comment by Fuzss** [comment]
That's Controllable's fault. It doesn't properly deal with events being cancelled when it's trying to move the hotbar (Console Experience is doing that for the "Hide Hud" feature). You need to disable the "Console Hotbar" setting in Controllable.
