### ISSUE TITLE
Chat links are offset from regular chat

### ISSUE THREAD

**Issue by WitheredWasabi** [Fuzss/consolehud#27]
![Inked2020-09-11_22 43 06_LI](https://user-images.githubusercontent.com/38932715/92988436-565abd80-f480-11ea-9449-923986193788.jpg)
(red dot is where my cursor was around)

**Comment by Fuzss** [comment]
Fixed in fc89620, version will be released on Curse hopefully soon

**Comment by BugmanBugman** [comment]
![2020-10-13_13 07 48](https://user-images.githubusercontent.com/40730042/95901865-92bc5a80-0d59-11eb-80fa-32121503cc28.png)
Was this fixed for sure? As you can see in the picture, my cursor is below the chat bar yet its bringing up the advancement tooltip

**Comment by BugmanBugman** [comment]
I think you might've only pushed the change for 1.15.2, since 1.16.3 still has it
