### ISSUE TITLE
[1.12.2] [Feature Request] Quark colored name compatibility?

### ISSUE THREAD

**Issue by Landiie** [Fuzss/consolehud#28]
I would love it if quark's colored name feature could show up on the hotbar! Here is a gif of what currently happens:

![colored name](https://user-images.githubusercontent.com/43101146/93460311-de353300-f897-11ea-9630-b0fd376d3992.gif)

(if the item is enchanted and color named, it will show the enchantment color but not quark's color name feature)

Thank you for taking your time to read this!

**Comment by Fuzss** [comment]
1.12.2 is no longer supported.
