### ISSUE TITLE
[1.16.1 - 1.16.3] Crash with Menu Companions

### ISSUE THREAD

**Issue by COMBOhrenovke** [Fuzss/consolehud#30]
Game crashes and blames Menu Companions as the reason, but ill put this error on both github pages.
[crash-2020-10-24_23.01.13-fml.txt](https://github.com/Fuzss/consoleexperience/files/5433772/crash-2020-10-24_23.01.13-fml.txt)

**Comment by Fuzss** [comment]
Fixed in a7a907a. Will be released as v1.7 on Curse soon.
