### ISSUE TITLE
Newer Forge versions crash

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/consolehud#31]
`Minecraft v1.16.3`
`Forge v34.1.33`
`Console Experience v1.6`

Newer Forge versions are crashing due to a Forge change:
[Crash Report](https://gist.github.com/WenXin20/5cf47782ee48d2077dffb1c3b2d9a03b)

**Comment by Fuzss** [comment]
Fixed in a7a907a. Will be released as v1.7 on Curse soon.
