### ISSUE TITLE
Classic bars doesn't work with console experience's consule hud tweaks

### ISSUE THREAD

**Issue by BugmanBugman** [Fuzss/consolehud#32]
![2020-10-31_22 59 38](https://user-images.githubusercontent.com/40730042/97794848-22249300-1bcd-11eb-96be-48ecb83dee49.png)
![2020-10-31_23 00 02](https://user-images.githubusercontent.com/40730042/97794849-2355c000-1bcd-11eb-9202-b89ba2087659.png)

**Comment by Fuzss** [comment]
There was a new compatibility mode setting added for hovering hotbar and hide hud in a7a907a. Mode 1 is the one that'll make classic bars work properly. The new version will be released as v1.7 on Curse asap.

**Comment by BugmanBugman** [comment]
You got no idea how happy this made me. Thanks for the early Christmas present
