### ISSUE TITLE
[1.16.4] tips.json in config folder generates empty.

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Fuzss/consolehud#33]
Forge version: 35.1.29
Minecraft Version: 1.16.4
Console Experience version: 1.7

Hello!

When I've been playing the latest version of your mod I noticed that whenever I would be in the loading screen added by this mod, it would just say "missingno" where the loading screen tip should be, like so: 
![Screenshot 2021-01-04 00 23 56](https://user-images.githubusercontent.com/64381954/103492570-c3290780-4e23-11eb-9c2c-0f1a64f831f0.png)
After looking in the config files I found the tips.json file to configure the loading screen tips and noticed it was completely empty. 

I've edited plenty of config files in the past to tweak modpacks to my liking but I have no idea how to write one from scratch.

Would you be able to add in some example tips to this file? It would allow me and others who don't know how to write these files from scratch to add our own tips in and get an idea of the format of how the tips should be written to work properly. (Note: Every other config file this mod generated has generated properly, it's just tips.json that is having this issue).

**Comment by Fuzss** [comment]
Seems to be a Windows related problem. The file as it should be can be found in the root of the mod jar. Only the copying itself seems to be the issue. Here is an exampe:

```json
[
  "Use seagrass to attract and breed sea turtles.",
  "You can breed Hoglins with Crimson Fungus, but it is dangerous!"
]
```

**Comment by The-Bernician-Lamb** [comment]
You're right! After looking in the mod jar using 7-zip I have been able to find the completed tips.json file with all tips in place. 

Copying it over manually seemed to do the trick:
![Screenshot 2021-01-04 11 22 21](https://user-images.githubusercontent.com/64381954/103530386-36ac3280-4e7f-11eb-82f1-ab2d34e19e53.png)
I have no idea why this file specifically is having a problem, when no other config file from this mod has had any problems being copied over. 

Thanks for your help! I appreciate it!

**Comment by Fuzss** [comment]
Can you please test if [this](https://mega.nz/file/HM0lXawR#WU-FuHvP5aJngq91nRK8hsUzBbjmYxC9WHAGVyYv_30) build fixes the issue?

**Comment by Fuzss** [comment]
Or [this](https://mega.nz/file/nJkCTYCR#a2CdVDvEMMqE2NQaWYMaINXOUKJICsJUiUO4DloYLf4). Please also send me the `latest.log` file.

**Comment by The-Bernician-Lamb** [comment]
Thanks! I'll have a look at those builds in a bit and report back with the results.

**Comment by The-Bernician-Lamb** [comment]
First file didn't work. Here is my latest log from this test:
[latest.log](https://github.com/Fuzss/consoleexperience/files/5788448/latest.log)

Will feedback about the second one in a little bit...

**Comment by The-Bernician-Lamb** [comment]
Second one didn't work either. Here is my log from that attempt:
[latest.log](https://github.com/Fuzss/consoleexperience/files/5788469/latest.log)

It appears to describe a null pointer exception when attempting to copy over tips.json

I hope this is of use to you!

If you need me to do anything else, Just let me know.

**Comment by Fuzss** [comment]
Alright, thanks! Please try [this](https://mega.nz/file/HclyXS5I#K0XEN6gqKoSxA-9NRFcb45W0YCFgB-5DD458wguDBz4) one as well.

**Comment by Fuzss** [comment]
And also [this](https://mega.nz/file/rUkiCKja#DOsp6HiG4D8swWIflTNzMZr0J8z1FoCSlhWDbbK8Ed8) one.
A already know what causes the issue, only question now is how to fix it.

**Comment by The-Bernician-Lamb** [comment]
No Luck with the third file:
[latest.log](https://github.com/Fuzss/consoleexperience/files/5788730/latest.log)

**Comment by The-Bernician-Lamb** [comment]
Fourth one fixed it! Everything copied over correctly!
[latest.log](https://github.com/Fuzss/consoleexperience/files/5788747/latest.log)

**Comment by Fuzss** [comment]
Thank you so much for your help!

**Comment by The-Bernician-Lamb** [comment]
No Problem! Thank YOU for making such great mods!

**Comment by The-Bernician-Lamb** [comment]
I have been able to confirm that this issue is fixed with the latest release on Curseforge.

Thanks again for your help!
