### ISSUE TITLE
Menu Notes say "missino"

### ISSUE THREAD

**Issue by Camawama** [Fuzss/consolehud#34]
The Menu Tips say "missino" everytime.

**Comment by Fuzss** [comment]
Duplicate of #33

**Comment by Fuzss** [comment]
Can you please test if [this](https://mega.nz/file/HM0lXawR#WU-FuHvP5aJngq91nRK8hsUzBbjmYxC9WHAGVyYv_30) build fixes the issue?

**Comment by Fuzss** [comment]
Or [this](https://mega.nz/file/nJkCTYCR#a2CdVDvEMMqE2NQaWYMaINXOUKJICsJUiUO4DloYLf4). Please also send me the `latest.log` file.
