### ISSUE TITLE
[1.12.2] Abyssalcraft items will deobf

### ISSUE THREAD

**Issue by SettingDust** [Fuzss/consolehud#36]
In inv
![image](https://user-images.githubusercontent.com/19922286/105936117-16dae980-608e-11eb-9d76-d146dbcad6c6.png)

In hand
![image](https://user-images.githubusercontent.com/19922286/105936176-2a865000-608e-11eb-9157-fa0aa8c73ef1.png)

It's displaying the actual info of a unknown item

1.12.2

**Comment by Fuzss** [comment]
1.12 unfortunately is no longer supported.
