### ISSUE TITLE
One minor but big thing is missing in this mod...

### ISSUE THREAD

**Issue by Cixon** [Fuzss/consolehud#37]
**Context:** This is just a mere suggestion, no bugs here.
_(had no place to write this tbh)_

If possible, I'd love to see these animations introduced into console experience!

Everyone who played back when 4J Studios was around, remembers that MC
shared the same animation for mining and fighting with a item in hand.

**Video:** https://youtu.be/7U1ehiueON8

**Comment by Fuzss** [comment]
I honestly can't really spot a difference between this and the current Java behavior. Maybe you can elaborate a little?

Also I'd prefer if suggestions would be kept on CurseForge, therefore closing this ticket. Feel free to repost your suggestion over there.
