### ISSUE TITLE
crash when using a golden chorus (chorus link mod), can't join the world anymore.

### ISSUE THREAD

**Issue by Wedge1453** [Fuzss/consolehud#38]
[crash-2021-03-08_20.40.00-client.txt](https://github.com/Fuzss/consoleexperience/files/6104278/crash-2021-03-08_20.40.00-client.txt)
EDIT: Chorus Warp not Link**

**Comment by Fuzss** [comment]
Probably easier to fix on their end, but I'll see that I catch that exception in the future.

Also your world is fine, this is just a client-side crash. In the meantime disable `Held Item Tooltips` for Console Experience, or remove the mod, and everything will launch as expected.

**Comment by Fuzss** [comment]
Just as a reference: freerangerstudios/choruswarps#3

**Comment by Wedge1453** [comment]
got it, thanks!

**Comment by Fuzss** [comment]
Added something to catch exceptions for this case, so closing this.
