### ISSUE TITLE
[Suggestion] Change to Default Effect Timer Color

### ISSUE THREAD

**Issue by ClankerTanker** [Fuzss/consolehud#44]
When using mods such as Farmer's Delight where effects are gained from consuming various food, the following occurs:

![Screenshot (758)](https://user-images.githubusercontent.com/71457231/120248510-7e27c680-c245-11eb-8525-4f9dbac31d2d.png)

While this isn't game-breaking, the timer is almost unreadable. Perhaps a color change to something more readable from a distance?

**Comment by Fuzss** [comment]
This feature has been turned into a standalone mod which fixes the whole effect time color issue (and also has plenty of options to configure how it is displayed): https://www.curseforge.com/minecraft/mc-mods/stylish-effects

This implementation will be removed from Console Experience in the near future.
