### ISSUE TITLE
Loading screen progress bar theme/style

### ISSUE THREAD

**Issue by madheadltd** [Fuzss/consolehud#46]
I have tested the mod and another similar mod "Bedrocklfy" for fabric, and I noticed that the style of progress bar and overall theme of loading screen not really matching the "Bedrock" theme, I personally prefer the fabric mod as it fits the Bedrock theme more, but I prefer playing on forge version. Is this intended or can it be enhanced/fixed?

![image](https://user-images.githubusercontent.com/85167236/123972028-18b62980-d9ed-11eb-9e2b-e6f816b0ec9b.png)
![image](https://user-images.githubusercontent.com/85167236/123972073-1fdd3780-d9ed-11eb-92f3-c76ece2a65c7.png)

Thanks, really like these kind of mods.

**Comment by Fuzss** [comment]
Console Experience attempts to mimic features from legacy console edition, not bedrock edition. The loading screen looks exactly as it does in legacy console edition. There are a few small things from bedrock edition, but the loading screen isn't one of those unfortunately. I don't think I'll be able to include it anytime soon.

**Comment by madheadltd** [comment]
> Console Experience attempts to mimic features from legacy console edition, not bedrock edition. The loading screen looks exactly as it does in legacy console edition. There are a few small things from bedrock edition, but the loading screen isn't one of those unfortunately. I don't think I'll be able to include it anytime soon.

Thank you for your reply, I might just keep using this mod while waiting another "Bedrocklfy" -like mod for forge come out.
