### ISSUE TITLE
[Suggestion] Add the Bedrock book GUI

### ISSUE THREAD

**Issue by zndrmn** [Fuzss/consolehud#47]
BEDROCK
![image](https://user-images.githubusercontent.com/77690119/127720174-ee652a7a-b215-4a53-8a78-6b084f38cc68.png)
JAVA
![image](https://user-images.githubusercontent.com/77690119/127720303-250dd19a-bc7c-4ece-9fef-4cf4288adbea.png)

**Comment by 6216lol** [comment]
use bedrockify as this mod is to emulate Legacy Console

**Comment by Fuzss** [comment]
Yeah, I like the suggestion, but I don't think Console Experience will continue in it's current form anyways, and such a feature isn't a priority. 

This suggestion is a much better fit for the Bedrockify mod, see: https://github.com/juancarloscp52/BedrockIfy/issues/114
