### ISSUE TITLE
Auto click with GoldenAgeCombat

### ISSUE THREAD

**Issue by ghost** [Fuzss/consolehud#50]
Can you add auto attack with swords like in legacy console edition when GoldenAgeCombat is installed ?

**Comment by Fuzss** [comment]
Auto attack is a feature for controllers, there are no plans to support controller exclusive features in Console Experience.

You can try to make this suggestion to some of the controller support mods though such as [Controllable](https://www.curseforge.com/minecraft/mc-mods/controllable).

**Comment by ghost** [comment]
I mean, not only with controller, you can spam click with a controller, so why not add the same auto autoclicker on mouse.
