### ISSUE TITLE
Loading Screen Not working in 1.12.2?

### ISSUE THREAD

**Issue by Dillonsmarty** [Fuzss/consolehud#51]
I don't know if these features were added in the 1.16 and the other new versions but I can't get the loading screen and other GUI stuff to work.
![Capt543535ure](https://user-images.githubusercontent.com/74514009/138003863-fbfb490f-0313-44d6-9284-fd63178b783a.PNG)
I also can't get the eating animation to work but I forgot to screenshot it.

**Comment by Dillonsmarty** [comment]
I also forgot to mention I am using Optifine and CJB Quick Craft mod to get it to seem more like xbox 360.

**Comment by Fuzss** [comment]
Loading screens were added in v1.7, eating animation in v1.6, latest versions for 1.12 is v1.4.
1.12 is no longer supported unfortunately.
