### ISSUE TITLE
1.13.2 Fails to load.

### ISSUE THREAD

**Issue by nazecham** [Fuzss/consolehud#54]
So I have a curseforge profile with some shaders and mods to get the game to feel like legacy console edition.
This mod looked like a cool mod to add, because of the features. I load up the mod, and I get this error.

![image](https://user-images.githubusercontent.com/109752332/180261028-72ef64d3-fa8f-45b7-974f-6b39a9a63b7a.png)

I am unsure why this error appears, I am not too familiar with Minecraft modding.
Is this a known issue? I looked on this GitHub page and it doesn't say anything.
Please help me with this issue. I have attached latest.log
[latest.log](https://github.com/Fuzss/consoleexperience/files/9160970/latest.log)

**Comment by Fuzss** [comment]
You need Forge 1.13.2-25.0.92 or newer, I'd recommend the latest build which is 1.13.2-25.0.223 if you really want to stick to 1.13.2.
