### ISSUE TITLE
Incompatability with Optifine's fast render option

### ISSUE THREAD

**Issue by IronPiston** [Fuzss/consolehud#8]
With the "Fast Render" setting enabled on Optifine, the game loads and the HUD disappears. Opening player inventory or hitting escape doesn't display their respective GUIs (they still function though). Disabling fast render stops this, and Optifine doesn't seem to have any other issues.

**Comment by geniiii** [comment]
perhaps it has something to do with Fast Render disabling FBOs? i don't think this mod is to blame for that, though

**Comment by Fuzss** [comment]
Was able to reproduce in early versions of Forge for 1.14.2, even without OptiFine. As of 1.14.4 there no longer seems to be any issue at all.
