### ISSUE TITLE
Console Hud 1.14.3

### ISSUE THREAD

**Issue by BuilderDan** [Fuzss/consolehud#9]
Seems like the Mod won't render anything for me in my 1.14.3 modpack. Inventory and any buttons don't render. I have to click blindly to leave the game. I think it might be some incompatibility between Console Hud and Cealus API (Since that's the only mod that I can think of in my pack that would interfere).

**Comment by Fuzss** [comment]
Can't test atm, but probably an issue within Forge. Try to update to the latest version. In case that doesn't help you can disable the hovering hotbar for now, that's most likely what's causing this.

**Comment by Fuzss** [comment]
Closing this now as obsolete since it only seems to be an issue with outdated beta versions of Forge.
